//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndInventory.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public System.Guid ItemUID { get; set; }
        public string ItemDesc { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<System.DateTime> ModifiedByOn { get; set; }
        public Nullable<int> DeletedByID { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    }
}
